# Generated by Django 3.1.5 on 2021-01-19 23:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment_follow_likes_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='post',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='post',
            name='starting_bid',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 1, 51, 5, 639154)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 1, 51, 5, 640154)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 20, 1, 51, 5, 638154)),
        ),
    ]
