# Generated by Django 3.1.5 on 2021-02-04 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210204_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_num',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 20, 38, 38, 187171)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 20, 38, 38, 188171)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 20, 38, 38, 185171)),
        ),
        migrations.AlterField(
            model_name='unlikes',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 4, 20, 38, 38, 189171)),
        ),
    ]
