# Generated by Django 3.1.5 on 2021-02-07 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210204_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 19, 35, 28, 102676)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 19, 35, 28, 102676)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 19, 35, 28, 87076)),
        ),
        migrations.AlterField(
            model_name='unlikes',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 19, 35, 28, 102676)),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('post_id', 'user_id')},
        ),
    ]
