# Generated by Django 3.1.5 on 2021-02-07 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210207_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 19, 36, 28, 793848)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 19, 36, 28, 809448)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 19, 36, 28, 793848)),
        ),
        migrations.AlterField(
            model_name='unlikes',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 19, 36, 28, 809448)),
        ),
    ]
