# Generated by Django 3.1.5 on 2021-02-07 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20210207_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 19, 46, 2, 727067)),
        ),
        migrations.AlterField(
            model_name='likes',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 19, 46, 2, 728067)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 19, 46, 2, 726067)),
        ),
        migrations.AlterField(
            model_name='unlikes',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 7, 19, 46, 2, 728067)),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set(),
        ),
    ]
